# Generated by Django 6.0.6 on 2026-06-13 05:07

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image de fond du hero (idealement 1920x1080px ou ratio 16:9)', upload_to='hero/%Y/%m/')),
                ('title', models.CharField(blank=True, help_text='Titre affiché sur le hero (laissez vide pour utiliser le titre par défaut du site)', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Sous-titre affiché sur le hero (laissez vide pour utiliser le sous-titre par défaut)', max_length=300)),
                ('cta_text', models.CharField(blank=True, default='Explorer nos remèdes', help_text="Texte du bouton d'appel à l'action", max_length=100)),
                ('cta_url', models.CharField(blank=True, default='/boutique/', help_text="URL du bouton d'appel à l'action", max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero - Slide',
                'verbose_name_plural': 'Hero - Slides',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
