# Generated by Django 6.0.6 on 2026-06-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['page', 'sort_order', '-created_at'], 'verbose_name': 'Hero - Slide', 'verbose_name_plural': 'Hero - Slides'},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='page',
            field=models.CharField(choices=[('home', "Page d'accueil"), ('login', 'Connexion'), ('register', 'Inscription'), ('forgot_password', 'Mot de passe oublié'), ('otp_verify', 'Vérification OTP')], default='home', help_text='Page sur laquelle ce hero sera affiché', max_length=30, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, help_text='Titre affiché sur le hero (laissez vide pour utiliser le titre par défaut)', max_length=200),
        ),
    ]
